/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Diego
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ArrayList<Icon> aryInstrucciones;
    private int     ContInstrucciones = 0;
    private Jugador jugador;
    public  boolean noIniciado = true;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        aryInstrucciones = new ArrayList<>();
        initComponents();
        interfazMenuPrincipal();
        //interfazCrearPartida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUnirseAPartida = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnCrearPartida = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        btnIniciarPartida = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txfIP = new javax.swing.JTextField();
        txfIngresarNombre = new javax.swing.JTextField();
        spnCantJugadores = new javax.swing.JSpinner();
        txaIPs = new javax.swing.JTextArea();
        btnAceptar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setMaximumSize(new java.awt.Dimension(466, 472));
        setMinimumSize(new java.awt.Dimension(466, 472));
        setPreferredSize(new java.awt.Dimension(472, 501));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUnirseAPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnUnirseAPartida.png"))); // NOI18N
        btnUnirseAPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUnirseAPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseAPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnirseAPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 231, 179, 48));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnInstrucciones.png"))); // NOI18N
        btnInstrucciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 305, 179, 48));

        btnCrearPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnCrearPartida.png"))); // NOI18N
        btnCrearPartida.setBorder(null);
        btnCrearPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 156, 179, 48));

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIzquierda.png"))); // NOI18N
        btnIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 432, 51, 27));

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnDerechaApagado.png"))); // NOI18N
        btnDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 432, 51, 27));

        btnIniciarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnUnirseAPartida1.png"))); // NOI18N
        btnIniciarPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 313, 139, 43));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnHome.png"))); // NOI18N
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 404, 57, 57));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnExit.png"))); // NOI18N
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 404, 57, 57));

        txfIP.setBackground(new java.awt.Color(0, 0, 0));
        txfIP.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        txfIP.setForeground(new java.awt.Color(0, 255, 204));
        txfIP.setText("192.168.XXX.XXX");
        txfIP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txfIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 178, 150, 30));

        txfIngresarNombre.setBackground(new java.awt.Color(0, 0, 0));
        txfIngresarNombre.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        txfIngresarNombre.setForeground(new java.awt.Color(0, 255, 204));
        txfIngresarNombre.setText("Jugador");
        txfIngresarNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txfIngresarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 138, 230, 30));

        spnCantJugadores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spnCantJugadores.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));
        getContentPane().add(spnCantJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 40, 30));

        txaIPs.setEditable(false);
        txaIPs.setBackground(new java.awt.Color(0, 0, 0));
        txaIPs.setColumns(20);
        txaIPs.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        txaIPs.setForeground(new java.awt.Color(255, 255, 0));
        txaIPs.setRows(5);
        getContentPane().add(txaIPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 420, 270));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unirseAPartida.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 466, 472));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        interfazMenuPrincipal();
        //ContInstruciones = 0;
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        interfazCrearPartida();
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void btnUnirseAPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseAPartidaActionPerformed
        interfazUnirseAPartida();
    }//GEN-LAST:event_btnUnirseAPartidaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        aryInstrucciones.add(ponerIcono("instrucciones"));
        aryInstrucciones.add(ponerIcono("instrucciones1"));
        aryInstrucciones.add(ponerIcono("instrucciones2"));
        aryInstrucciones.add(ponerIcono("instrucciones3"));
    }//GEN-LAST:event_formWindowOpened

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        interfazInstrucciones();
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        interfazBtnDerecho();
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        interfazBtnIzquierdo();
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        if (btnIniciarPartida.getIcon().toString().equals(obtenerDireccionIcono("btnCrearPartida1"))){
            jugador.CrearPartida(txfIngresarNombre.getText(), (Integer)spnCantJugadores.getValue(), this);
            btnIniciarPartida.setVisible(false);
            spnCantJugadores.setVisible(false);
            txfIngresarNombre.setVisible(false);
            btnHome.setVisible(false);
            try {
                IPsElegibles();
            } catch (SocketException | UnknownHostException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            jugador.UnirseAPartida(txfIngresarNombre.getText(), txfIP.getText(), this);
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    private void interfazMenuPrincipal(){
        lblFondo.setIcon(ponerIcono("menuPrincipal"));
        btnIniciarPartida.setVisible(false);
        btnIzquierda.setVisible(false);
        btnDerecha.setVisible(false);
        txfIP.setVisible(false);
        txfIngresarNombre.setVisible(false);
        spnCantJugadores.setVisible(false);
        txaIPs.setVisible(false);
        btnAceptar.setVisible(false);
        btnCrearPartida.setVisible(true);
        btnUnirseAPartida.setVisible(true);
        btnInstrucciones.setVisible(true);
    }
    
    private void interfazCrearPartida(){
        btnCrearPartida.setVisible(false);
        btnUnirseAPartida.setVisible(false);
        btnInstrucciones.setVisible(false);
        btnIzquierda.setVisible(false);
        btnDerecha.setVisible(false);
        txfIP.setVisible(false);
        txaIPs.setVisible(false);
        btnAceptar.setVisible(false);
        lblFondo.setIcon(ponerIcono("crearPartida"));
        txfIngresarNombre.setVisible(true);
        spnCantJugadores.setVisible(true);
        btnIniciarPartida.setVisible(true);
        btnIniciarPartida.setIcon(ponerIcono("btnCrearPartida1"));
    }
    
    private void interfazUnirseAPartida(){
        btnCrearPartida.setVisible(false);
        btnUnirseAPartida.setVisible(false);
        btnInstrucciones.setVisible(false);
        btnIzquierda.setVisible(false);
        btnDerecha.setVisible(false);
        spnCantJugadores.setVisible(false);
        txaIPs.setVisible(false);
        btnAceptar.setVisible(false);
        lblFondo.setIcon(ponerIcono("unirseAPartida"));
        txfIngresarNombre.setVisible(true);
        txfIP.setVisible(true);
        btnIniciarPartida.setVisible(true);
        btnIniciarPartida.setIcon(ponerIcono("btnUnirseAPartida1"));
    }
    
    private void interfazInstrucciones(){
        btnCrearPartida.setVisible(false);
        btnUnirseAPartida.setVisible(false);
        btnInstrucciones.setVisible(false);
        txfIngresarNombre.setVisible(false);
        txfIP.setVisible(false);
        btnIniciarPartida.setVisible(false);
        spnCantJugadores.setVisible(false);
        txaIPs.setVisible(false);
        btnAceptar.setVisible(false);
        lblFondo.setIcon(aryInstrucciones.get(ContInstrucciones));
        btnIzquierda.setVisible(true);
        btnDerecha.setVisible(true);
        if (btnIzquierda.getIcon().toString().equals(obtenerDireccionIcono("btnIzquierda")) && ContInstrucciones == 0){
            btnIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnIzquierda.setIcon(ponerIcono("btnIzquierdaApagado"));
            btnDerecha.setIcon(ponerIcono("btnDerecha"));
        }
    }
    
    private void interfazBtnDerecho(){
        btnIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIzquierda.setIcon(ponerIcono("btnIzquierda"));
        ContInstrucciones++;
        if (ContInstrucciones >= 3){
            ContInstrucciones = 3;
            btnDerecha.setIcon(ponerIcono("btnDerechaApagado"));
            btnDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
        lblFondo.setIcon(aryInstrucciones.get(ContInstrucciones));
    }
    
    private void interfazBtnIzquierdo(){
        btnDerecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDerecha.setIcon(ponerIcono("btnDerecha"));
        ContInstrucciones--;
        if (ContInstrucciones <= 0){
            ContInstrucciones = 0;
            btnIzquierda.setIcon(ponerIcono("btnIzquierdaApagado"));
            btnIzquierda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
        lblFondo.setIcon(aryInstrucciones.get(ContInstrucciones));
    }
    
    private void IPsElegibles () throws SocketException, UnknownHostException{
        txaIPs.setEditable(true);
        txaIPs.setText("IPs elegibles para los demás jugadores: " + "\n");
        Enumeration<NetworkInterface> n = NetworkInterface.getNetworkInterfaces();
        for (; n.hasMoreElements();)
        {
            NetworkInterface e = n.nextElement();

            Enumeration<InetAddress> a = e.getInetAddresses();
            for (; a.hasMoreElements();)
            {
                InetAddress addr = a.nextElement();
                System.out.println("  " + addr.getHostAddress());
                if (esIP("" + addr.getHostAddress()))
                    txaIPs.append("\n" + addr.getHostAddress());
            }
        }
        txaIPs.setEditable(false);
    }
    
    private boolean esIP(String IP){
        int posicionPunto = 0;
            for (int i = 0; i < 3; i++){
                if (IP.indexOf('.', posicionPunto) == -1)
                    return false;
                posicionPunto = IP.indexOf('.', posicionPunto);
                posicionPunto++;
            }
            return IP.indexOf('.', posicionPunto) == -1;
    }
    
    public ImageIcon ponerIcono (String nombreImg){
        return new javax.swing.ImageIcon(getClass().getResource("/imagenes/" + nombreImg + ".png"));
    }
    
    public String obtenerDireccionIcono (String nombreImg){
        return getClass().getResource("/imagenes/" + nombreImg + ".png") + "";
    }

    public Jugador getJugador() {
        return jugador;
    }

    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }
    
    public void settxaIPs(boolean bool){
        txaIPs.setVisible(bool);
    }
    
    public void setBtnAceptar(boolean bool){
        btnAceptar.setVisible(bool);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnUnirseAPartida;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JSpinner spnCantJugadores;
    private javax.swing.JTextArea txaIPs;
    private javax.swing.JTextField txfIP;
    private javax.swing.JTextField txfIngresarNombre;
    // End of variables declaration//GEN-END:variables
}
